version: '3.8'
services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env



  backend:
    # image: schlyomin/foodgram-backend:latest     < -- в следующей строке правильный адрес образа на докерхабе
    image: schlyomin/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    # container_name: frontend     < -- это не мешает, но и пользы не приносит. Имя берется из предыд.строки
    # в следующей строке правильный адрес образа на докерхабе
    image: schlyomin/frontend:v.1.0
    # build:                           < -- отключил сборку фронта из папок, пусть собирается из образа 
    #   context: ../frontend          < -- это тоже не нужно, если собираем из образа
    volumes:
      - ../frontend/:/app/result_build/
    # depends_on:
    #   - backend

  nginx:
    image: nginx
    restart: always
    # container_name: nginx   < -- не мешает, но и пользы не приносит. Имя берется из предыд.строки
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend


volumes:
  static_value:
  media_value:
  db_value: