version: '3.8'
services:

  db:
    image: postgres:12.4
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env



  backend:
    image: schlyomin/backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env


  frontend:
    image: schlyomin/frontend:v.1.0
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend


volumes:
  static_value:
  media_value:
  db_value: