# Generated by Django 3.2.18 on 2023-03-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='colorcode',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
    ]
